# Pulumi Collect Action
#
# Collects Pulumi preview artifacts and builds deployment matrices for requested stacks.
# This action downloads preview markers and artifacts, then builds a matrix of
# successful previews for deployment.
#
# Usage:
# ```yaml
# - uses: jmmaloney4/workflows/.github/actions/pulumi-collect@main
#   id: collect
#   with:
#     stacks: '["stage","prod"]'
# - name: Use collected matrix
#   run: echo '${{ steps.collect.outputs.matrix }}'
# ```

name: 'Collect Pulumi previews and build deploy matrix'
description: 'Download success markers and previews, summarize results, and output deployment matrix'

inputs:
  stacks:
    description: 'JSON array of stack names to collect (e.g., ["stage","prod"])'
    required: true
  working-directory:
    description: 'Working directory for operations'
    required: false
    default: '.'

outputs:
  matrix:
    description: 'JSON matrix of {project, stack} objects ready for deployment'
    value: ${{ steps.build.outputs.matrix }}
  summary-path:
    description: 'Path to the generated summary file'
    value: ${{ steps.build.outputs.summary-path }}

runs:
  using: 'composite'
  steps:
  - name: Download success markers
    uses: actions/download-artifact@v4
    with:
      pattern: 'preview-ok-*'
      path: preview-ok

  - name: Download preview artifacts
    uses: actions/download-artifact@v4
    with:
      pattern: 'preview-*'
      path: preview-previews

  - name: Build deployment matrix
    id: build
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      # Use the extracted script for building the deployment matrix
      "${{ github.action_path }}/../../scripts/actions/pulumi-collect/build-matrix.sh" \
        '${{ inputs.stacks }}' \
        '${{ inputs.working-directory }}'

  - name: Upload summary artifact
    uses: actions/upload-artifact@v4
    with:
      name: pulumi-preview-summary
      path: ${{ steps.build.outputs.summary-path }}
      if-no-files-found: warn