# Push images produced by Nix flake image packages (*-image)

name: "Nix Image Push"
description: "Push images to a registry using nix copyTo-style runners"

inputs:
  images-dir:
    description: "Directory containing generated *.env descriptors"
    required: false
    default: "images"
  image-repo-prefix:
    description: "Registry repo prefix (e.g., ghcr.io/owner/repo)"
    required: true
  github-token:
    description: "Token for registry auth (e.g., GITHUB_TOKEN)"
    required: true
  actor:
    description: "Actor used for registry auth; defaults to env GITHUB_ACTOR"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - id: push
      name: Push images via nix
      shell: bash
      env:
        INPUT_IMAGES_DIR: ${{ inputs.images-dir }}
        INPUT_IMAGE_REPO_PREFIX: ${{ inputs.image-repo-prefix }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_ACTOR: ${{ inputs.actor }}
      run: bash "$GITHUB_ACTION_PATH/scripts/push.sh"
