# Pulumi Setup Action
#
# A composite action that sets up Pulumi with authentication, dependencies,
# and environment configuration for infrastructure deployments.
#
# Usage:
# ```yaml
# - uses: jmmaloney4/workflows/.github/actions/pulumi-setup@main
#   with:
#     login-backend: gs://my-pulumi-state
#   env:
#     GOOGLE_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
#     GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}
# ```

name: 'Pulumi Setup'
description: 'Setup Pulumi with authentication, dependencies, and environment configuration'

inputs:
  login-backend:
    description: 'Pulumi backend URL to login to (e.g., gs://bucket, s3://bucket, or blank for Pulumi Cloud)'
    required: false
    default: ''
  install-dependencies:
    description: 'Install project dependencies (npm/pnpm install, pip install, etc.)'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for Pulumi commands'
    required: false
    default: '.'
  enable-gcp-auth:
    description: 'Enable GCP authentication via Workload Identity'
    required: false
    default: 'true'

outputs:
  pulumi-version:
    description: 'Installed Pulumi version'
    value: ${{ steps.pulumi-info.outputs.version }}
  backend-url:
    description: 'Pulumi backend URL in use'
    value: ${{ steps.pulumi-info.outputs.backend }}

runs:
  using: 'composite'
  steps:

  - name: Authenticate to Google Cloud
    if: ${{ inputs.enable-gcp-auth == 'true' && env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER != '' }}
    uses: google-github-actions/auth@v2
    with:
      workload_identity_provider: ${{ env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ env.GOOGLE_SERVICE_ACCOUNT_EMAIL }}

  - name: Setup Google Cloud SDK
    if: ${{ inputs.enable-gcp-auth == 'true' && env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER != '' }}
    uses: google-github-actions/setup-gcloud@v2

  - name: Install project dependencies
    if: ${{ inputs.install-dependencies == 'true' }}
    shell: bash
    run: |
      "${{ github.action_path }}/../../scripts/actions/pulumi-setup/install-dependencies.sh" \
        "${{ inputs.working-directory }}"

  - name: Login to Pulumi backend
    shell: bash
    run: |
      "${{ github.action_path }}/../../scripts/actions/pulumi-setup/login-backend.sh" \
        "${{ inputs.login-backend }}" \
        "${{ inputs.working-directory }}"

  - name: Get Pulumi information
    id: pulumi-info
    shell: bash
    run: |
      "${{ github.action_path }}/../../scripts/actions/pulumi-setup/get-pulumi-info.sh" \
        "${{ inputs.working-directory }}" \
        "${{ inputs.enable-gcp-auth }}"
