name: Pulumi Setup
description: Authenticate to GCP and prepare environment for Pulumi via Nix
inputs:
  google_workload_identity_provider:
    description: Workload Identity Provider resource
    required: true
  google_service_account_email:
    description: Service account email
    required: true
  nodejs_package_manager:
    description: 'Node.js package manager: "pnpm", "npm", or "none"'
    required: true
runs:
  using: composite
  steps:
    - uses: jmmaloney4/toolbox/.github/actions/nix-setup@main
    - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        workload_identity_provider: ${{ inputs.google_workload_identity_provider }}
        service_account: ${{ inputs.google_service_account_email }}
    - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
      with:
        install_components: gke-gcloud-auth-plugin
    - shell: bash
      run: |
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> "$GITHUB_ENV"
        echo "PULUMI_NODEJS_PACKAGE_MANAGER=${{ inputs.nodejs_package_manager }}" >> "$GITHUB_ENV"
    # Set PULUMI_NODEJS_PACKAGE_MANAGER for Pulumi's internal auto-detection (defense-in-depth)
