name: Create ADR Placeholder
description: Creates placeholder ADR file on main branch with link to PR

inputs:
  adr_files:
    description: Path to file containing list of ADR files (one per line)
    required: true
  pr_url:
    description: The pull request URL
    required: true
  pr_number:
    description: The pull request number (optional, used for commit message)
    required: false
  commit_message:
    description: Custom commit message (optional). Use {{adr_numbers}} placeholder.
    required: false
  base_branch:
    description: Base branch to reserve ADR numbers on (e.g., main)
    required: false
    default: main

runs:
  using: composite
  steps:
  - shell: bash
    run: ${{ github.action_path }}/script.sh
    env:
      ADR_FILES: ${{ inputs.adr_files }}
      PR_URL: ${{ inputs.pr_url }}
      PR_NUMBER: ${{ inputs.pr_number }}
      COMMIT_MESSAGE: ${{ inputs.commit_message }}
      BASE_BRANCH: ${{ inputs.base_branch }}
