name: Push GHCR Images
description: Downloads image artifacts and pushes to GHCR with appropriate tags.
inputs:
  ghcr-namespace:
    description: 'GHCR namespace (defaults to github.repository)'
    required: false
    type: string
  repository:
    description: 'Repository to operate on (defaults to github.repository)'
    required: false
    type: string
  ref:
    description: 'Git ref for tagging (defaults to github.ref)'
    required: false
    type: string
runs:
  using: "composite"
  steps:
  - shell: bash
    run: $GITHUB_ACTION_PATH/main.sh
    env:
      GHCR_NAMESPACE: ${{ inputs.ghcr-namespace }}
      REPOSITORY: ${{ inputs.repository }}
      REF: ${{ inputs.ref }}
