/**
 * Worker script template for uptime monitoring with D1 storage, KV state
 * tracking, and webhook alerting on failure-state transitions.
 *
 * ADR-020: Cloudflare Worker Uptime Monitor
 */

/**
 * Configuration for a single monitored endpoint.
 */
export interface MonitorTarget {
	/**
	 * Unique identifier for this monitor (alphanumeric, dashes).
	 * Used as monitor_id in D1 and as KV key prefix.
	 */
	id: string;
	/** Full URL to probe (e.g., "https://grafana.example.com/healthz"). */
	url: string;
	/**
	 * HTTP method. @default "GET"
	 */
	method?: "GET" | "HEAD";
	/**
	 * Expected HTTP status codes. Probe is "ok" if status is in this list.
	 * @default [200]
	 */
	expectedCodes?: number[];
	/**
	 * Maximum response time in milliseconds before marking as failed.
	 * 0 = no timeout enforcement (Worker fetch timeout still applies).
	 * @default 0
	 */
	timeoutMs?: number;
	/**
	 * Substring to search for in the response body.
	 * If set, the probe is "ok" only when the body contains this string.
	 * Only applies to GET requests (HEAD has no body).
	 */
	expectedBody?: string;
	/**
	 * Request headers to send with the probe.
	 */
	headers?: Record<string, string>;
}

/**
 * Generate the Worker script code for uptime monitoring.
 *
 * The generated script:
 * 1. Probes each configured endpoint (fetch with timing).
 * 2. Inserts a row into D1 for each probe result.
 * 3. Reads/writes failure streak state from KV.
 * 4. Fires webhook alerts on state transitions (healthy -> unhealthy or vice versa).
 */
export function generateMonitorScript(monitors: MonitorTarget[]): string {
	const monitorsJson = JSON.stringify(
		monitors.map((m) => ({
			id: m.id,
			url: m.url,
			method: m.method ?? "GET",
			expectedCodes: m.expectedCodes ?? [200],
			timeoutMs: m.timeoutMs ?? 0,
			expectedBody: m.expectedBody ?? null,
			headers: m.headers ?? null,
		})),
		undefined,
		"\t",
	);

	return `
/**
 * UptimeMonitor - Synthetic HTTP probe with D1 storage and webhook alerting
 * Generated by @jmmaloney4/sector7 UptimeMonitor component
 * ADR-020: Cloudflare Worker Uptime Monitor
 */

const MONITORS = ${monitorsJson};

const ALERT_THRESHOLD = 3;
const RECOVERY_THRESHOLD = 1;

export default {
	async scheduled(controller, env, ctx) {
		const results = [];

		for (const monitor of MONITORS) {
			const result = await probe(monitor, env);
			results.push(result);
		}

		// Insert all results into D1 in a single batch
		if (results.length > 0) {
			const placeholders = results.map(() => "(?, ?, ?, ?, ?, ?, ?, ?)").join(", ");
			const values = results.flatMap((r) => [
				r.ts,
				r.monitor_id,
				r.url,
				r.ok ? 1 : 0,
				r.status,
				r.latency_ms,
				r.error ?? null,
				r.region_hint ?? null,
			]);

			await env.DB.prepare(
				\`INSERT INTO probe_results (ts, monitor_id, url, ok, status, latency_ms, error, region_hint) VALUES \${placeholders}\`
			)
				.bind(...values)
				.run();
		}

		// Check alert conditions for each monitor using KV state
		for (const result of results) {
			await checkAndAlert(result, env, ctx);
		}
	},
};

async function probe(monitor, env) {
	const start = Date.now();
	const ts = new Date().toISOString();
	let ok = false;
	let status = 0;
	let latencyMs = 0;
	let error = null;

	try {
		const controller = new AbortController();
		const timeout = monitor.timeoutMs > 0 ? setTimeout(() => controller.abort(), monitor.timeoutMs) : undefined;

		const headers = new Headers(monitor.headers ?? {});
		const response = await fetch(monitor.url, {
			method: monitor.method,
			headers,
			signal: controller.signal,
			redirect: "follow",
		});

		if (timeout) clearTimeout(timeout);

		status = response.status;
		latencyMs = Date.now() - start;
		ok = monitor.expectedCodes.includes(status);

		// Check body content if specified and method is GET
		if (ok && monitor.expectedBody && monitor.method === "GET") {
			const text = await response.text();
			// Only keep first 500 chars for snippet
			ok = text.includes(monitor.expectedBody);
		}
	} catch (e) {
		latencyMs = Date.now() - start;
		error = e instanceof Error ? e.message : String(e);
	}

	return {
		ts,
		monitor_id: monitor.id,
		url: monitor.url,
		ok,
		status,
		latency_ms: latencyMs,
		error,
		region_hint: env.REGION_HINT ?? null,
	};
}

async function checkAndAlert(result, env, ctx) {
	const kvKey = \`streak:\${result.monitor_id}\`;
	let state;

	try {
		const raw = await env.KV.get(kvKey, "json");
		state = raw ?? { consecutive_failures: 0, last_status: "healthy", last_ts: null };
	} catch {
		state = { consecutive_failures: 0, last_status: "healthy", last_ts: null };
	}

	if (result.ok) {
		state.consecutive_failures = 0;
	} else {
		state.consecutive_failures++;
	}

	const previousStatus = state.last_status;
	state.last_status = result.ok ? "healthy" : "unhealthy";
	state.last_ts = result.ts;

	// Write updated state back to KV (non-blocking)
	ctx.waitUntil(env.KV.put(kvKey, JSON.stringify(state)));

	// Fire webhook on state transitions
	if (previousStatus !== state.last_status) {
		// unhealthy -> healthy (recovery)
		if (state.last_status === "healthy" && previousStatus === "unhealthy") {
			ctx.waitUntil(sendWebhook(env, {
				type: "recovery",
				monitor_id: result.monitor_id,
				url: result.url,
				ts: result.ts,
				previous_status: previousStatus,
				current_status: state.last_status,
				message: \`Monitor \${result.monitor_id} recovered\`,
			}));
		}
		// healthy -> unhealthy (alert)
		else if (state.last_status === "unhealthy" && state.consecutive_failures >= ALERT_THRESHOLD) {
			ctx.waitUntil(sendWebhook(env, {
				type: "alert",
				monitor_id: result.monitor_id,
				url: result.url,
				ts: result.ts,
				previous_status: previousStatus,
				current_status: state.last_status,
				consecutive_failures: state.consecutive_failures,
				error: result.error,
				status: result.status,
				message: \`Monitor \${result.monitor_id} is unhealthy (\${state.consecutive_failures} consecutive failures)\`,
			}));
		}
	}
}

async function sendWebhook(env, payload) {
	const webhookUrl = env.WEBHOOK_URL;
	if (!webhookUrl) return;

	try {
		await fetch(webhookUrl, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(payload),
		});
	} catch (e) {
		console.error("Failed to send webhook:", e);
	}
}
`.trim();
}
