name: Nix Setup
description: Install Nix and enable flakehub cache for GitHub Actions
inputs:
  runs-on:
    description: Runner label to determine if runs-on/actions@v2 should be used
    required: true
    type: string
  cache:
    description: Enable FlakeHub cache (set to 'false' for self-hosted runners with cache already configured)
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - if: ${{ contains(inputs.runs-on, 'runner=') }} && ${{ contains(inputs.runs-on, 's3-cache') }}
      uses: runs-on/action@742bf56072eb4845a0f94b3394673e4903c90ff0 # v2.1.0
      with:
        show_costs: true
        sccache: s3
    - uses: DeterminateSystems/nix-installer-action@4a754ab0c192f4d12cf88b5954b9dd13fd2d612e # main
    - if: ${{ inputs.cache == 'true' }}
      uses: DeterminateSystems/flakehub-cache-action@1f9a51a2959d3e26c7838c6f3bf9f48acae525ea # main
      # TODO: Fix this
      # with:
      # use-gha-cache: enabled
