name: Nix Setup
description: Install Nix and enable flakehub cache for GitHub Actions
inputs:
  runs-on:
    description: Runner label to determine if runs-on/actions@v2 should be used
    required: true
    type: string
  cache:
    description: Enable FlakeHub cache (set to 'false' for self-hosted runners with cache already configured)
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - if: ${{ contains(inputs.runs-on, 'runner=') }} && ${{ contains(inputs.runs-on, 's3-cache') }}
      uses: runs-on/action@cd2b598b0515d39d78c38a02d529db87d2196d1e # v2.0.3
      with:
        show_costs: true
        sccache: s3
    - uses: DeterminateSystems/nix-installer-action@main
    - if: ${{ inputs.cache == 'true' }}
      uses: DeterminateSystems/flakehub-cache-action@main
      # TODO: Fix this
      # with:
      # use-gha-cache: enabled
