name: Nix Setup
description: Install Nix and enable flakehub cache for GitHub Actions
inputs:
  runs-on:
    description: Runner label to determine if runs-on/actions@v2 should be used
    required: true
    type: string
  cache:
    description: Enable FlakeHub cache (set to 'false' for self-hosted runners with cache already configured)
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - if: ${{ contains(inputs.runs-on, 'runner=') }} && ${{ contains(inputs.runs-on, 's3-cache') }}
      uses: runs-on/action@742bf56072eb4845a0f94b3394673e4903c90ff0 # v2.1.0
      with:
        show_costs: true
        sccache: s3
    - uses: DeterminateSystems/nix-installer-action@b66b36319cc6fde4ea85edd583b088c65d6b8710 # main
    - if: ${{ inputs.cache == 'true' }}
      uses: DeterminateSystems/flakehub-cache-action@f053b608e8a623da93029482500353079142e628 # main
      # TODO: Fix this
      # with:
      # use-gha-cache: enabled
