name: '📦 pnpm'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write
jobs:
  pnpm:
    uses: jmmaloney4/sector7/.github/workflows/pnpm.yml@9d71ec06b6d6e9204b8df4585e65de5323826c16 # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
      dry_run: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      target: release
