name: '📦 pnpm'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write
jobs:
  pnpm:
    uses: jmmaloney4/sector7/.github/workflows/pnpm.yml@61fa58a027d96afc7c5c9a2953ab54dd3bb42ad4 # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
      dry_run: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      target: release
