name: 📝 adr (dogfood)
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: write
  pull-requests: write
jobs:
  adr-management:
    if: github.actor != 'github-actions[bot]'
    uses: jmmaloney4/toolbox/.github/workflows/adr-management.yml@73b0c490c72bbea2941cf44eb9b6bb127878c7ef # main
    with:
      repository: ${{ github.repository }}
      ref: refs/pull/${{ github.event.pull_request.number }}/head
      base_ref: ${{ github.event.pull_request.base.ref }}
      head_ref: ${{ github.event.pull_request.head.ref }}
      adr_glob: 'docs/internal/designs/*.md'
      pr_number: ${{ github.event.pull_request.number }}
      pr_url: ${{ github.event.pull_request.html_url }}
