name: '📦 pnpm'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
permissions:
  contents: read
  packages: write
jobs:
  pnpm:
    uses: jmmaloney4/toolbox/.github/workflows/pnpm.yml@bc7846003f39ec61654d70f5cfd1413046b3b763 # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
      dry_run: ${{ !startsWith(github.ref, 'refs/tags/v') }}
