name: '❄️ nix'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  nix:
    uses: jmmaloney4/sector7/.github/workflows/nix.yml@9d71ec06b6d6e9204b8df4585e65de5323826c16 # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
