name: '❄️ nix'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  nix:
    uses: jmmaloney4/toolbox/.github/workflows/nix.yml@bc7846003f39ec61654d70f5cfd1413046b3b763 # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
