name: '❄️ nix'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  nix:
    uses: jmmaloney4/sector7/.github/workflows/nix.yml@5d4e3062f23cc6aef0a7a65e510329ad927ad8e6 # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
