name: '📦 pnpm'
on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  pnpm:
    uses: jmmaloney4/toolbox/.github/workflows/pnpm.yml@main
    with:
      runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
      dry_run: ${{ !startsWith(github.ref, 'refs/tags/v') }}