name: 📌 add to project (dogfood)
on:
  issues:
    types: [opened, reopened, transferred, labeled]
  pull_request:
    types: [opened, reopened, labeled]
permissions:
  contents: read
jobs:
  add-to-project:
    uses: jmmaloney4/sector7/.github/workflows/add-to-project.yml@5d4e3062f23cc6aef0a7a65e510329ad927ad8e6 # main
