/**
 * Worker script template for serving static files from R2 with Cache API.
 * Phase 2: R2 serving with edge caching and configurable TTL.
 * Phase 3 (ADR-011): Optional redirect rules injected into generated script.
 */

/**
 * A single HTTP redirect rule.
 */
export interface RedirectRule {
	/** The hostname that triggers the redirect (e.g., "www.example.com"). */
	fromHost: string;
	/** The hostname to redirect to (e.g., "example.com"). */
	toHost: string;
	/** HTTP status code for the redirect (301, 302, 307, or 308). @default 301 */
	statusCode?: 301 | 302 | 307 | 308;
}

/**
 * Generate the Worker script code for serving static files from R2 with Cache API.
 *
 * Parameters
 * ----------
 * bucketBinding : string
 *     The R2 bucket binding name (e.g., "R2_BUCKET")
 * prefix : string, optional
 *     Optional prefix to prepend to all R2 object keys
 * redirects : RedirectRule[], optional
 *     Optional list of host-level redirect rules, evaluated before R2 serving
 *
 * Returns
 * -------
 * string
 *     The Worker script code as a string
 */
export function generateWorkerScript(
	bucketBinding: string,
	prefix?: string,
	redirects?: RedirectRule[],
): string {
	// Use JSON.stringify to safely embed prefix — it produces a
	// double-quoted string that is safe for JS template interpolation.
	const safePrefix = prefix ? JSON.stringify(prefix) : undefined;

	// Generate redirect block
	const redirectBlock =
		redirects && redirects.length > 0
			? redirects
					.map((r) => {
						const status = r.statusCode ?? 301;
						const fromHost = JSON.stringify(r.fromHost);
						const toHost = JSON.stringify(r.toHost);
						return `\t\tif (url.hostname === ${fromHost}) {
			const redirectUrl = new URL(request.url);
			redirectUrl.hostname = ${toHost};
			return Response.redirect(redirectUrl.toString(), ${status});
		}`;
					})
					.join("\n")
			: null;

	return `
/**
 * WorkerSite - Static file server with R2 backend and Cache API
 * Generated by @jmmaloney4/sector7 WorkerSite component
 * Phase 2: Edge caching with configurable TTL
 */

interface Env {
	${bucketBinding}: R2Bucket;
	CACHE_TTL_SECONDS: string;
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		try {
			const url = new URL(request.url);
${redirectBlock ? `\n${redirectBlock}\n` : ""}
			// 1. Path normalization - remove leading slash
			let objectKey = url.pathname.slice(1);

			// 2. Directory index handling
			if (objectKey === '' || objectKey.endsWith('/')) {
				objectKey += 'index.html';
			}

			// 2.5. Prepend prefix if configured
			${safePrefix ? `objectKey = ${safePrefix} + '/' + objectKey;` : "// No prefix configured"}

			// 3. Cache API check (requires custom domain)
			const cache = caches.default;
			const cacheKey = new Request(url.toString(), { method: 'GET' });
			let response = await cache.match(cacheKey);

			if (response) {
				// Cache HIT - return immediately with debug header
				const headers = new Headers(response.headers);
				headers.set('X-Cache-Status', 'HIT');
				return new Response(response.body, {
					status: response.status,
					statusText: response.statusText,
					headers,
				});
			}

			// 4. Cache MISS - fetch from R2
			const object = await env.${bucketBinding}.get(objectKey);

			// 5. Handle 404
			if (!object) {
				return new Response('Not Found', { status: 404 });
			}

			// 6. Build response with metadata
			response = createResponse(object, objectKey, 200, 'MISS', env);

			// 7. Async cache storage (non-blocking)
			// Clone response because R2 body streams are single-use
			ctx.waitUntil(cache.put(cacheKey, response.clone()));

			return response;
		} catch (error) {
			// Log error for debugging (visible in Workers logs)
			console.error('WorkerSite error:', error);

			// Return 500 error to client
			return new Response('Internal Server Error', {
				status: 500,
				headers: { 'Content-Type': 'text/plain' }
			});
		}
	},
};

/**
 * Create HTTP Response from R2 object with proper headers
 */
function createResponse(object: R2ObjectBody, objectKey: string, status: number, cacheStatus: string, env: Env): Response {
	const headers = new Headers();

	// Content-Type from R2 metadata
	if (object.httpMetadata?.contentType) {
		headers.set('Content-Type', object.httpMetadata.contentType);
	} else {
		// Fallback based on file extension
		const contentType = guessContentType(objectKey);
		headers.set('Content-Type', contentType);
	}

	// ETag for cache validation
	headers.set('ETag', object.httpEtag);

	// Cache-Control with configurable TTL
	const maxAge = env.CACHE_TTL_SECONDS || '31536000';
	headers.set('Cache-Control', \`public, max-age=\${maxAge}, immutable\`);

	// Last-Modified
	if (object.uploaded) {
		headers.set('Last-Modified', object.uploaded.toUTCString());
	}

	// Observability header
	headers.set('X-Cache-Status', cacheStatus);

	return new Response(object.body, { status, headers });
}

/**
 * Guess content type from file extension
 */
function guessContentType(key: string) {
	// Get the basename (after last '/')
	const base = key.substring(key.lastIndexOf('/') + 1);
	const dot = base.lastIndexOf('.');
	const ext = (dot > 0) ? base.substring(dot + 1).toLowerCase() : '';
	const types = {
		html: 'text/html; charset=utf-8',
		css: 'text/css; charset=utf-8',
		js: 'application/javascript; charset=utf-8',
		json: 'application/json; charset=utf-8',
		png: 'image/png',
		jpg: 'image/jpeg',
		jpeg: 'image/jpeg',
		gif: 'image/gif',
		svg: 'image/svg+xml',
		ico: 'image/x-icon',
		woff: 'font/woff',
		woff2: 'font/woff2',
		ttf: 'font/ttf',
		eot: 'application/vnd.ms-fontobject',
		pdf: 'application/pdf',
		txt: 'text/plain; charset=utf-8',
		webp: 'image/webp',
		avif: 'image/avif',
		mp4: 'video/mp4',
		webm: 'video/webm',
	};
	return types[ext || ''] || 'application/octet-stream';
}
`.trim();
}
